// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfbbbwutkrshtboxedbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYmJid3V0a3JzaHRib3hlZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNjkzOTQsImV4cCI6MjA3NDk0NTM5NH0.ps-XCqawniRYHY2SmTErZYCF9MXmij8d1a4lcjAh2dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});